export type HouseCard = {
  price: number
  numBeds: number
  numBaths: number
  sqFt: number
  status: 'Active' | 'InActive' | 'New'
  address: string
  mlsID: string
  mlsData: string
  description: string
  img: string
}

export const houseListings: HouseCard[] = [
  {
    price: 650000,
    numBeds: 4,
    numBaths: 3,
    sqFt: 2850,
    status: 'New',
    address: '5729 E Fernan Hill Rd, Coeur D Alene, ID, 83814',
    mlsID: '20242708',
    mlsData: 'WINDERMERE HAYDEN LLC, Chad Salsbury',
    description: 'House for Sale',
    img: '/src/assets/house-1.jpg',
  },
  {
    price: 879000,
    numBeds: 5,
    numBaths: 4,
    sqFt: 3565,
    status: 'Active',
    address: '892 Lakeshore Drive, Crystal Bay, NV, 89402',
    mlsID: '20242709',
    mlsData: 'CHASE INTERNATIONAL, Sarah Smith',
    description: 'Waterfront Property',
    img: '/src/assets/house-9.jpg',
  },
  {
    price: 425000,
    numBeds: 3,
    numBaths: 2,
    sqFt: 1950,
    status: 'New',
    address: '1234 Pine Valley Rd, Reno, NV, 89511',
    mlsID: '20242710',
    mlsData: 'DICKSON REALTY, Michael Johnson',
    description: 'Single Family Home',
    img: '/src/assets/house-4.jpg',
  },
  {
    price: 1250000,
    numBeds: 6,
    numBaths: 5,
    sqFt: 4800,
    status: 'Active',
    address: '456 Lakefront Blvd, Incline Village, NV, 89451',
    mlsID: '20242711',
    mlsData: 'SIERRA SOTHEBYS, Emily Williams',
    description: 'Luxury Estate',
    img: '/src/assets/house-2.jpg',
  },
  {
    price: 550000,
    numBeds: 3,
    numBaths: 2,
    sqFt: 2200,
    status: 'InActive',
    address: '789 Mountain View Dr, Carson City, NV, 89703',
    mlsID: '20242712',
    mlsData: 'RE/MAX REALTY, David Brown',
    description: 'Mountain View Home',
    img: '/src/assets/house-3.jpg',
  },
  {
    price: 925000,
    numBeds: 4,
    numBaths: 3.5,
    sqFt: 3200,
    status: 'New',
    address: '321 Lakeview Terrace, South Lake Tahoe, CA, 96150',
    mlsID: '20242713',
    mlsData: 'COLDWELL BANKER, Jennifer Davis',
    description: 'Lake View Property',
    img: '/src/assets/house-4.jpg',
  },
  {
    price: 749000,
    numBeds: 4,
    numBaths: 3,
    sqFt: 2850,
    status: 'Active',
    address: '567 Forest Ridge Rd, Stateline, NV, 89449',
    mlsID: '20242714',
    mlsData: 'BERKSHIRE HATHAWAY, Robert Wilson',
    description: 'Forest View Home',
    img: '/src/assets/house-5.jpg',
  },
  {
    price: 599000,
    numBeds: 3,
    numBaths: 2.5,
    sqFt: 2400,
    status: 'InActive',
    address: '432 Eagle Ridge Ln, Sparks, NV, 89436',
    mlsID: '20242715',
    mlsData: 'KELLER WILLIAMS, Amanda Thompson',
    description: 'Ridge View Home',
    img: '/src/assets/house-6.jpg',
  },
  {
    price: 1450000,
    numBeds: 5,
    numBaths: 4.5,
    sqFt: 5200,
    status: 'New',
    address: '789 Lakeside Drive, Zephyr Cove, NV, 89448',
    mlsID: '20242716',
    mlsData: 'CHASE INTERNATIONAL, Mark Anderson',
    description: 'Lakeside Mansion',
    img: '/src/assets/house-7.jpg',
  },
  {
    price: 475000,
    numBeds: 3,
    numBaths: 2,
    sqFt: 1850,
    status: 'Active',
    address: '123 Valley View Ct, Carson City, NV, 89701',
    mlsID: '20242717',
    mlsData: 'RE/MAX REALTY, Lisa Parker',
    description: 'Valley Home',
    img: '/src/assets/house-8.jpg',
  },
]
